<a href="https://www.kaggle.com/code/heemalichaudhari/learning-pytorch?scriptVersionId=115851332" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Everything about PyTorch 

# Tensors

At the heart of PyTorch is the `Tensor`, a multi-dimensional matrix containing elements of a single data type. PyTorch provides a large number of functions for operating on and manipulating tensors.



# Autograd

One of the key features of PyTorch is the `autograd` package, which provides automatic differentiation of tensor operations. This allows for the creation of complex neural network architectures with minimal effort, and makes it easy to compute gradients during the backpropagation phase of training.



# nn module

The `nn` module in PyTorch provides a convenient way to define and train neural networks. It includes a variety of predefined layers and cost functions, as well as utilities for constructing and training networks.



# Optim

The `optim` package in PyTorch provides a variety of optimization algorithms for training neural networks. These algorithms can be used to update the weights and biases of the network based on the computed gradients.



# Data loading and preprocessing

PyTorch provides a number of tools for loading and preprocessing data, including the `torchvision` package, which contains a number of popular datasets and image transformation functions.



### This below example defines a neural network with a single fully-connected (`Linear`) layer, with a single output. We will randomly initialize the weights and biases of the network, and then use the `autograd` functionality to compute gradients and update the weights and biases during the training process.

# Importing Required Libraries

In [1]:
import torch
import torch.nn as nn

# Define the network

In [2]:
class Net(nn.Module):
    def __init__(self, input_size, output_size):
        super(Net, self).__init__()
        self.fc = nn.Linear(input_size, output_size)

    def forward(self, x):
        x = self.fc(x)
        return x

# Create the network

In [3]:
net = Net(input_size=10, output_size=1)

# Print the initialized weights and biases

In [4]:
print(net.fc.weight)
print(net.fc.bias)

Parameter containing:
tensor([[ 0.0830, -0.1064, -0.2382, -0.0809,  0.2651, -0.0968,  0.2775, -0.2870,
          0.0299, -0.2231]], requires_grad=True)
Parameter containing:
tensor([0.1781], requires_grad=True)


# Set the network in training mode

In [5]:
net.train()

Net(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)

# Define the loss function and optimizer

In [6]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

# Generate some random input data

In [7]:
input_data = torch.randn(100, 10)

# Set the target output

In [8]:
target_output = torch.randn(100, 1)

# Training loop

In [9]:
for i in range(500):
    # Forward pass
    output = net(input_data)

    # Compute the loss
    loss = loss_fn(output, target_output)

    # Print the loss every 50 iterations
    if i % 50 == 0:
        print(f'iteration {i}, loss = {loss.item():.4f}')

    # Zero the gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update the weights and biases
    optimizer.step()

iteration 0, loss = 1.3790
iteration 50, loss = 1.0578
iteration 100, loss = 1.0578
iteration 150, loss = 1.0578
iteration 200, loss = 1.0578
iteration 250, loss = 1.0578
iteration 300, loss = 1.0578
iteration 350, loss = 1.0578
iteration 400, loss = 1.0578
iteration 450, loss = 1.0578


# Set the network in eval mode

In [10]:
net.eval()

Net(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)

# Generate some new input data

In [11]:
new_input_data = torch.randn(1, 10)

# Get the predicted output

In [12]:
predicted_output = net(new_input_data)

# Print the predicted output

In [13]:
print(predicted_output)

tensor([[0.2549]], grad_fn=<AddmmBackward0>)


# I hope this example helps to give you a sense of how to define and train a neural network in PyTorch. Let me know if you have any questions or if you would like to see more examples in the comment section!



